name: Trigger Release

on:
  workflow_dispatch:
  release:
    # We'll run this workflow when a new GitHub release is created
    types: [ released ]

jobs:
  publish_archives:
    runs-on: ubuntu-latest

    if: github.repository == 'daniel-rusu/pods4k'
    permissions:
      contents: read

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
      - name: Publish the artifacts
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: ./gradlew publishAllPublicationsToMavenCentralRepository --no-parallel --no-configuration-cache
